favourites = ("TALE_OF_US", "UMEK", "ANJUNA", "ISMA", "BUUREN", "DIGWEED","SAIZ", "PETE_TONG", "PETE.TONG", "DOORN", "GUY_J", "GUY.J", "NICK_WARREN", "NICK.WARREN", "SASHA", "MACEO_PLEX",
            "ADVISOR", "NEWIK", "MUSIC_KILLERS", "MINILOGUE", "PIG_DAN", "WATERMAT", "SHOWTEK", "MANTEY","TODD_TERJE", "MATTZO",
            "WESTBAM", "BERGHEAU", "BOOKA_SHADE", "BLIZZARD", "RANK1", "KOLETZKI", "KALKBRENNER", "REX_MUNDI", "ATB", "DASH_BERLIN", "ORJAN_NIELSEN",
            "GARETH_EMERY", "BLOMQVIST", "NADJALIND", "EXTRAWELT", "SCAVO", "KOLLEKTIV", "BERLIN", "DAHLBACK", "BENASSI", "VARIOUS",
            "COMPILED", "COMPILATION", "GUETTA", "HARRIS", "DUMONT", "CLAPTONE", "ZEDD_", "MARK_KNIGHT", "SHEPARD", "FEDDE_LE_GRAND", "ROGER_SHAH", "KYAU", "ABOVE",
            "BEST", "SELECTED", "SELECTION", "EXCLUSIVE", "DIXON", "_HEIDI", "HAWTIN", "GARRIX", "BEN_KLOCK", "TROXLER", "EATS_EVERYTHING", "COLLECTION",
            "HOT_SINCE", "MARCO_CAROLA", "KLARTRAUM", "MAYA_JANE_COL", "SVEN_VATH", "JACK_MASTER", "JAY_LUMEN", "NINA_KRAVIZ", "GARNIER", "LIEBING",
            "DAMIAN_LAZARUS", "CARL_COX", "LUCIANO", "LEE_BURRIDGE", "JORIS_VOORN", "BUTCH", "ZABIELA", "CATZ", "CATTANEO", "JEFF_MILLS",
            "JUSTIN_MARTIN", "LAWLER", "PACO_OSUNA", "TANZMANN", "DEETRON", "DEEP", "BENN_FINN", "TIMO_MAAS", "PICKS", "FABRIC",
            "GLOBAL_UNDERGROUND", "MOBY", "SERIES", "HOXTON", "ESSENTIAL", "MOONBEAM", "RA-TOP", "TRACKS", "BUDAI",
            "HUNGARY", "BUDAPEST", "_SOUNDS", "PODCAST", "MANTZUR", "VANNELLI", "HAWTIN", "TRENTEM", "CHYMERA", "SCUBA", "GUY_GERBER", "ZUSAMMENKLANG",
            "EULBERG, HAZENDONK", "RILEY_REINHOLD", "_TOP", "CD_POOL", "TRANCE", "RESIDENT", "ADVISOR", "FABRIK", "WILLCOX", "TYDI", "SUNBEAM", "ANTHOLOGY",
            "ADRIATIQUE", "MARLO", "BUDAKID", "YOTTO", "BICEP", "GHEIST", "THRILLSEEKERS", "KLARTRAUM", "DOSEM", "BUDAKID", "EULBERG", "BABIC", "AUDIOJACK",
            "CHART", " RA ", "_RA_", "_TOP", " TOP ", "TECHNO", "BREJCHA", "TENSAL", "BEATPORT", "TRAXSOURCE", "KASSAR", "TAPIA")

banned = ("HARDSTYLE", "GOA", "DRUM_AND_BASS", "_PSY_", "90S", "TRAP_", "TANZ", "CHILLHOUSE", "RETRO","HOT_DANCE", "EDM")
